### ISSUE TITLE
Terminal themes?

### ISSUE THREAD

**Issue by ivancuric** [will-stone/Plastic-Theme#14]
Gotta say I love the new colors in the terminal.
Any chance of making a separate iterm / terminal theme with Plastic colors?

**Comment by will-stone** [comment]
Sure. I was thinking this could be separate repo but that may be a bit overkill. I'll change the folder structure to be by app, then this can be a mini-monorepo for all things Plastic; opening it up for themes for other editors too.

**Comment by kayteh** [comment]
semi-unrelated, the roundabout here is funny to me.

i wanted my terminal colors on plastic
OP wants plastic colors on their terminal

**Comment by lowmess** [comment]
Just stumbled upon Plastic today, and I _needed_ a terminal theme that matched. So I made one for Hyper, if anyone is still looking: https://github.com/lowmess/hyper-plastic

@will-stone thanks for providing the color map in the README, it made this unbelievably easy!

**Comment by will-stone** [comment]
@lowmess nice! Thanks. I'll add a link to your theme when I get around to updating the site. If you could add a screenshot to your README (that I can steal later), that'd be great 😄

**Comment by lowmess** [comment]
@will-stone no problem! meant to do that with the initial commit 😅 it's up there now!

**Comment by flrnprz** [comment]
I'll leave it here instead of opening another issue. First of all, Plastic is my main vscode theme from some time on, I love it! That's why I made a port for vim/neovim: https://github.com/flrnprz/candid.vim

I called it different because added light theme and some lightly differences, and didn't want to confuse people. Thanks for this wonderful theme!

**Comment by Happin3ss** [comment]
I tried to convert this into  Jetbrains theme by using they colorSchemeTool but turned out it cannot be used. It only can convert the theme into .tmTheme. I'm not sure is there any way around that I can port this into Jetbrains? Thanks for help.

**Comment by dok42** [comment]
Here's the color scheme for Windows Terminal
```
{
    "name": "Plastic",
    "cursorColor": "#A9B2C3",
    "selectionBackground": "#424751",
    "background": "#21252b",
    "foreground": "#A9B2C3",
    "black": "#21252B",
    "blue": "#61AFEF",
    "cyan": "#56B6C2",
    "green": "#98C379",
    "purple": "#B57EDC",
    "red": "#E06C75",
    "white": "#A9B2C3",
    "yellow": "#D19A66",
    "brightBlack": "#5F6672",
    "brightBlue": "#1085FF",
    "brightCyan": "#08E8DE",
    "brightGreen": "#69C52E",
    "brightPurple": "#8B00FF",
    "brightRed": "#D74E42",
    "brightWhite": "#D4D7D9",
    "brightYellow": "#E9D16C"
}
```
Got inspired (I literally copied 😄 ) from @lowmess Hyper version ;)

**Comment by will-stone** [comment]
Okay, still early days but you can be the first to know about https://plastictheme.com/
This includes instructions on installing themes for both iTerm and Terminal.app. I plan to theme more apps, and I'm still debating what colours to use for bright ANSI, but that can be a different issue.
Thanks all 😄
