### ISSUE TITLE
A suggestion on the background color

### ISSUE THREAD

**Issue by awkj** [will-stone/Plastic-Theme#163]
In my most commonly used three themes, default-dark, codesandbox, plastic, plastic color scheme is I think the most elegant, but always feel that the background color and the code itself is not strong enough contrast, the background color is somewhat to the blue, I hope the author can rely on adjusting the background color to black some, increase the contrast, the following is a comparison of the three themes.

default theme
![image (2)](https://user-images.githubusercontent.com/9017743/113480020-c8e6c580-94c4-11eb-8014-841a0b03bcf8.png)

codesandbox 
![image](https://user-images.githubusercontent.com/9017743/113480028-d439f100-94c4-11eb-8b32-36e1b4842d7e.png)

plastic
![image (1)](https://user-images.githubusercontent.com/9017743/113480032-db60ff00-94c4-11eb-9b2e-9e4075811d1b.png)

**Comment by will-stone** [comment]
Thanks for using Plastic. I've been using Plastic for nearly four years so I don't think I could change its background colour now. You can tweak this yourself in your VSCode settings using:

```json
{
  "workbench.colorCustomizations": {
    "editor.background": "#ff0000"
  }
}
```
